config/routes.rb
Rails.application.routes.draw do
  get 'errors/index'

  get 'settings/edit'
  post 'settings/update'

  get '', to: 'quotes#index'
  get 'quotes/update'
  get 'quotes/start_updates'
  get 'quotes/stop_updates'

  get 'stock_reports/generate'
  get 'stock_reports', to: 'stock_reports#index'
  get 'stock_reports/download/:id', to: 'stock_reports#download'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/error.rb
class Error < ApplicationRecord
end

app/models/quote.rb
class Quote < ApplicationRecord
end

app/models/scheduled_task.rb
class ScheduledTask
  require 'rufus-scheduler'

  @@tasks = {}

  def self.tasks
    @@tasks
  end

  def self.create_task(symbol, interval, &block)
    @@tasks[symbol] = ScheduledTask.new(interval, &block)
  end

  def initialize(interval, &block)
    @scheduler = Rufus::Scheduler.new
    @interval = interval
    @block = block
    schedule_task
  end

  def interval
    @interval
  end
  def interval=(value)
    @interval = value
    stop
    start
  end

  def scheduled?
    @job.scheduled?
  end

  def stop
    @job.unschedule if @job.scheduled?
  end

  def start
    schedule_task unless @job.scheduled?
  end



  def run
    @block.call(1)
  end

  private
  def schedule_task
    job_id = @scheduler.every @interval do
      run
    end

    @job = @scheduler.job(job_id)
  end

end

app/models/setting.rb
class Setting < ApplicationRecord

  validates :quote_update_interval,
            presence: true,
            numericality: {only_integer: true, greater_than: 0, less_than_or_equal_to: 60}

end

app/models/stock_report.rb
class StockReport < ApplicationRecord

  def self.build_report(report_type)
    report = StockReport.new
    data = get_report_data

    report.report = report_type.new.create do
      heading 'Stock Report'
      data.each_key do |key|
        quotes = data[key]
        sub_heading key
        table do
          table_heading do
            table_cells 'Date & Time (UTC)', 'Ask', 'Bid'
          end
          quotes.each do |quote|
            table_row do
              table_cells quote.created_at.strftime('%d/%m/%Y %H:%M'), quote.ask, quote.bid
            end
          end
        end
      end
    end

    report.save
  end

  def self.get_report_data
    Quote.where("created_at > ?", Time.now.utc - 1.hour).group_by{|r| r.name}
  end
end

app/models/text_report.rb
class TextReport

  def create(&block)
    @text = ''
    instance_eval(&block)
    return @text
  end

  def heading(text)
    text = text.to_s
    @text += '-' * text.length + "\r\n"
    @text += text.upcase + "\r\n"
    @text += '-' * text.length + "\r\n\r\n"
  end

  def sub_heading(text)
    text = text.to_s
    @text += text.upcase + "\r\n"
    @text += '-' * text.length + "\r\n"
  end

  def paragraph(text)
    text = text.to_s
    @text += text + "\r\n\r\n"
  end

  def table(&block)
    @text += Table.new.create(&block)
  end

  class Table

    def create(&block)
      @text = ''
      instance_eval(&block).to_s
      @text += "\r\n"
      return @text
    end

    def table_row(&block)
      @text += TableRow.new.create(false, &block) + "\r\n"
    end

    def table_heading(&block)
      @text += TableRow.new.create(true, &block) + "\r\n"
    end

    class TableRow

      def create(is_heading, &block)
        @text = ''
        @underline = ''
        @is_heading = is_heading
        instance_eval(&block).to_s
        @text += "\r\n" + @underline if @is_heading
        return @text
      end

      def table_cell(text)
        if @is_heading
          @text += text.to_s.upcase + "\t"
          @underline += '-' * text.length + "\t"
        else
          @text += text.to_s + "\t"
        end
      end

      def table_cells(*values)
        values.each do |value|
          table_cell(value)
        end
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def index
    @errors = Error.all
  end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  def index
    @stock_quotes = {}
    @errors = Error.where('created_at > ?', Time.now.utc - 1.hour)
    @task = ScheduledTask.tasks[:update_quotes]
    stocks = Quote.select(:name).distinct.order(:name)
    stocks.each do |s|
      @stock_quotes[s.name] = Quote.where(name: s.name).limit(5).order(created_at: :desc);
    end
  end

  def update
    YahooServiceHelper.update_stock_quotes_now
    redirect_to({:action => 'index'})
  end

  def stop_updates
    ScheduledTask.tasks[:update_quotes].stop
    redirect_to({:action => 'index'})
  end

  def start_updates
    ScheduledTask.tasks[:update_quotes].start
    redirect_to({:action => 'index'})
  end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  def edit
    @setting = Setting.order(created_at: :desc).first
  end

  def update
    @setting = Setting.order(created_at: :desc).first
    if @setting.update(update_params)
      redirect_to controller: 'quotes', action: 'index'
    else
      render 'edit'
    end

    ScheduledTask.tasks[:update_quotes].interval = @setting.quote_update_interval.to_s + 'm'
  end

  private
  def update_params
    params.require(:setting).permit(:quote_update_interval)
  end
end

app/controllers/stock_reports_controller.rb
class StockReportsController < ApplicationController
  def generate
    StockReport.build_report(TextReport)
    redirect_to({:action => "index"})
  end

  def index
    @reports = StockReport.order(created_at: :desc)
  end

  def download
    id = params[:id]
    report = StockReport.find(id)
    send_data report.report, :filename => report.created_at.to_s + '_report.txt', :type => 'text/plain'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/stock_reports_helper.rb
module StockReportsHelper
end

app/helpers/yahoo_service_helper.rb
module YahooServiceHelper

  @@stocks = ['NZDUSD=X', 'NZDAUD=X', 'NZDEUR=X', 'NZDGBP=X', 'NZDJPY=X']

  def self.get_stock_quotes
    url = "https://query.yahooapis.com/v1/public/yql?q=select * from yahoo.finance.quotes where symbol in ('#{@@stocks.join("','")}')&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys&callback="
    url.gsub!(' ', '%20').gsub!("'", '%22')

    begin
      result = HTTParty.get(url, :verify => false).parsed_response['query']['results']['quote']
    rescue Exception => e
      Error.new(message: e.message).save
      return
    end

    quotes = []
    result.each do |q|
      quotes.append Quote.new(:ask => q['Ask'], :bid => q['Bid'], :name => q['Name'], :symbol => q['Symbol'])
    end
    return quotes
  end

  def self.update_stock_quotes_now
    quotes = get_stock_quotes
    quotes.each {|q| q.save} if quotes
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Finance</title>
    <%= csrf_meta_tags %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/quotes/index.html.erb
<h1>Quotes</h1>

<%= link_to 'Update Now', {:action => 'update'} %> |
<%= link_to 'Reports', {:controller => 'stock_reports', :action => 'index'} %> |
<%= link_to 'Settings', {:controller => 'settings', :action => 'edit' } %> |
<%= link_to 'Errors', {:controller => 'errors', :action => 'index'} %>
<% if @task.scheduled? %>
    | <%= link_to 'Stop Updates', {:action => 'stop_updates'} %>
<% else %>
    | <%= link_to 'Start Updates', {:action => 'start_updates'} %>
<% end %>

<%if @errors.count > 0 %>
    <h3><%= pluralize(@errors.count, 'error') %> downloading quotes in the last hour</h3>
<% end %>

<% @stock_quotes.each_key do |key| %>
    <h2><%= key %></h2>

    <table>
      <tr>
        <th>Time (UTC)</th>
        <th>Ask Price</th>
        <th>Bid Price</th>
      </tr>
      <% @stock_quotes[key].each do |quote| %>
          <tr>
            <td><%= quote.created_at.strftime('%d/%m/%Y %H:%M') %></td>
            <td><%= quote.ask %></td>
            <td><%= quote.bid %></td>
          </tr>
      <% end %>
    </table>

<% end %>

app/views/settings/edit.html.erb
<h1>Edit Settings</h1>

<%= form_for :setting, url: settings_update_path do |f| %>
    <% if @setting.errors.any? %>
        <div id="error_explanation">
          <h2>Settings could not be saved</h2>
          <ul>
              <% @setting.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
          </ul>
        </div>
    <% end %>

    <div>
      <%= f.label :quote_update_interval %>
      <%= f.text_field :quote_update_interval %>
    </div>

    <div>
      <%= f.submit %>
    </div>

<% end %>

app/views/stock_reports/index.html.erb
<h1>Reports</h1>

<%= link_to 'Generate', {:action => 'generate'} %>

<ul>
  <% @reports.each do |report| %>
    <li><%= report.created_at.strftime('%d/%m/%Y %H:%M') %> <%= link_to 'Download', {:action => 'download', :id => report.id} %></li>
  <% end %>
</ul>